---
title: "Reproducibility Seurat Clustering"
author: "Celina Geiss and Christof Seiler"
format: html
date: now
editor: source
embed-resources: true
execute:
  warning: false
---

# Setup

```{r}
library(dplyr)
library(Seurat)
library(patchwork)
library(scater)
library(BiocSingular)
library(stringr)

seed <- 23
n_dim <- 100
set.seed(seed)
```

## Helper

Helper function to avoid sign flip. This is just a heuristic and is not guaranteed to work.

```{r}
NormalizePCASigns <- function(object, reduction = "pca") {
  
  loadings <- Loadings(object, reduction = reduction)
  embeddings <- Embeddings(object, reduction = reduction)
  
  for (i in seq_len(ncol(loadings))) {
    
    max_idx <- which.max(abs(loadings[, i]))
    
    if (loadings[max_idx, i] < 0) {
      loadings[, i] <- loadings[, i] * -1
      embeddings[, i] <- embeddings[, i] * -1
    }
  }
  
  object[[reduction]]@feature.loadings <- loadings
  object[[reduction]]@cell.embeddings <- embeddings
  object
  
}
```

Helper function to overwrite Seurat with Bioconductor.

```{r}
OverwriteSeurat <- function(object, sce, reduction = "pca") {
  
  embeddings <- reducedDim(sce, "PCA")
  colnames(embeddings) <- paste0("PC_", 1:n_dim)
  object[[reduction]]@cell.embeddings <- embeddings
  loadings <- attr(reducedDim(sce, "PCA"), "rotation")
  colnames(loadings) <- paste0("PC_", 1:n_dim)
  object[[reduction]]@feature.loadings <- loadings
  object[[reduction]]@stdev <- attr(reducedDim(sce, "PCA"), "percentVar")
  object
  
}
```

## Tutorial

Check reproducibility issue in Seurat clustering [tutorial](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html).

```{r}
# load
pbmc.data <- Read10X(data.dir = "filtered_gene_bc_matrices/hg19/")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k",
                           min.cells = 3, min.features = 200)
pbmc.data[c("CD3D", "TCL1A", "MS4A1"), 1:30]

# select and transform
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)

# PCA in Seurat 
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc), 
               approx = FALSE, # will be overwritten by the Bioconductor PCA
               npcs = n_dim, seed.use = seed)

# PCA in Bioconductor
pbmc_sce <- as.SingleCellExperiment(pbmc)
pbmc_sce <- runPCA(pbmc_sce,
                   subset_row = VariableFeatures(object = pbmc),
                   exprs_values = "scaledata",
                   ncomponents = n_dim,
                   #BSPARAM = ExactParam()  # exact SVD
                   BSPARAM = IrlbaParam()  # approximate SVD with irlba
                   #BSPARAM = RandomParam() # approximate SVD with rsvd
                   ) 
pbmc <- OverwriteSeurat(pbmc, pbmc_sce)

# align PCA signs
pbmc <- NormalizePCASigns(pbmc)
DimPlot(pbmc, reduction = "pca") + NoLegend()

# cluster
pbmc <- FindNeighbors(pbmc, dims = 1:n_dim, seed.use = seed)
pbmc <- FindClusters(pbmc, resolution = 0.5, random.seed = seed)

# visualize clusters
pbmc <- RunUMAP(pbmc, dims = 1:n_dim, seed.use = seed)

# individual clusters
DimPlot(pbmc, reduction = "umap")
```

Explore loadings.

```{r}
pbmc |> 
  Loadings() |> 
  head()
```

Save embeddings for followup analysis.

```{r}
cpu <- try(system("lscpu | grep 'Model name'", intern = TRUE))
cpu_name <- cpu |> 
  str_detect("AMD") |>
  ifelse("AMD", "Intel") |> 
  str_to_lower()
write.csv(Embeddings(pbmc), file = paste0(cpu_name, ".csv"), row.names = FALSE)
```

## Reproducibility

```{r}
.libPaths()
sessionInfo()
extSoftVersion()
cpu
```
